### ISSUE TITLE
کرش اپلیکیشن اندروید در release variant

### ISSUE THREAD

**Issue by shiraliali** [tapsellorg/TapsellPlusSDK-ReactNativePlugin#11]
<div dir='rtl'>
درود
اپلیکیشن توی release variant کرش میکنه و من پروژه سمپل رو بررسی کردم و ران گرفتم مشکلی توی دیباگ و ریلیز نبود به دلیل اینکه با نسخه های قدیمی تر بیلد شده `dependency` های متفاوتی داره اما به نظر میرسه شما بایید مجددا از اول روی پروژه با نسخه ریکت نیتیو 0.63.4 به بالا تست کنید (اضافه کردن لایبرری روی پروژه جدید) ظاهرا با نسخه های جدیدتر سازگار نیست و تنها راه اینه که یه پروژه جدید `initialize` کنید و `SDK` رو از ابتدا اضافه کنید.

به محض حذف لایبرری از اپلیکیشن مشکل برطرف میشه از تمام راه حل های موجود در وبسایت های مختلف و گیتهاب هم استفاده کردیم و مشکل مرتفع نشد.

</div>

**Comment by shiraliali** [comment]
این مورد رو فراموش کردم بگم ، حتی زمانی که توی پروژه import هم نشده توی یه اسکرین صرفا dependency نصب هست توی پروژه کرش میکنه

**Comment by mahdi-malv** [comment]
با وجود ادموب؟

**Comment by shiraliali** [comment]
بله به صورت دیفالت طبق مستندات
ولی اینکه صرفا دپندنسی نصب باشه و حتی اینیشالایز نشده و کرش میکنه مهمه

**Comment by mahdi-malv** [comment]
اینکه چه کرشی میکنه هم مهمه
لطفا اگر ممکنه متن کرش هم ضمیمه بشه

همچنین بدون وجود ادموب هم این کار رو انجام بدید ببینید آیا باز هم کرش میکنه؟

**Comment by shiraliali** [comment]
مشکل رو توی ریلیز حل شد و بنر نمایش داده میشه منتهی در حالت دیباگ علی رغم راهنمایی های داکیومنت شما و توضیحات شما و جستجو در اینترنت متاسفانه هنوز راه حلی پیدا نشده که توی دیباگ خطا مترو سرور نده.

**Comment by mahdi-malv** [comment]
منظورتون #10 هست؟ کلوز شده که

**Comment by shiraliali** [comment]
اره توی [آخرین رپلای](https://github.com/tapsellorg/TapsellPlusSDK-ReactNativePlugin/issues/10#issuecomment-909582907) رفرنسی که به ایشو ریپو ریکت نیتیو داده شده صرفا خطارو انگار ناپدید میکنه اما حلش نمیکنه که بعد تر این رو متوجه شدم و مجددا باز نکردم دیگه. کلا با این سولوشن اپ توی حالت دیباگ خطا نمیده اما عملا ارتباطی با مترو سرور نداره و هیچ لاگی رو نمی تونی بگیری و کلا دولوپر منو هم قاعدتا قابل دسترسی هیچ کدوم از آپشن هاش.

**Comment by mahdi-malv** [comment]
رو اپلیکیشن سمپل هم این مشکل رو میتونید تولید کنید؟
تو چه حالتی؟
