### ISSUE TITLE
🐛  ناسازگاری: React-native 0.64.x conflict

### ISSUE THREAD

**Issue by kamyabsoft** [tapsellorg/TapsellPlusSDK-ReactNativePlugin#12]
<div dir='rtl'>

**شرح باگ در پلاگین**:
با ورژن جدید react native سازگار نیست و موقع نصب ارور میده

code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: awesomeproject@0.0.1
npm ERR! Found: react-native@0.64.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"0.63.4" from react-native-tapsell-plus@2.1.3
npm ERR! node_modules/react-native-tapsell-plus
npm ERR!   react-native-tapsell-plus@"*" from the root project

</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

درود
من این ارور رو نتونستم تولید کنم و بدون مشکل با آپگرید ری‌اکت نیتیو سمپل ران شد
ورژن NodeJs تون چیه؟

</div>

**Comment by mahdi-malv** [comment]
@kamyabsoft وضعیت مشکل به چه صورت هست؟

**Comment by kamyabsoft** [comment]
ورژن نود من v16.3.0 هست
من یه پروژه خام ریکت نیتیو بالا آوردم و زمانی که دارم تپسل نصب میکنم ارور بالا میده و به نظرم میگه ناسازگاری ورژن تپسل با ریکت نیتیو
اگه ممکنه ورژن خود ریکت نیتیو داخل پروژه را آپدیت کنید

**Comment by mahdi-malv** [comment]
با نود ۱۴ هم میتونید تستش کنید؟

**Comment by mahdi-malv** [comment]
و اینم اضافه کنم نمیشه ری اکت نیتیو رو آپدیت کرد تو پلاگین
چون ۰.۶۴ مینیم ۲۱ رو برای پروژه اندروید میخواد که همه‌ی کاربرا این رو نمیخوان

**Comment by kamyabsoft** [comment]
نمیشه اختصاصی برای ما آپدیت کنید و دو ورژن بزارید الان خیلی ها به این ارور خوردن و نمیتونن انجام بدم نمونه اش نظرات این سایت را مشاهده کنید
https://reactapp.ir/courses/%D8%AF%D9%88%D8%B1%D9%87-%D9%87%D8%A7%DB%8C-%D8%A2%D9%85%D9%88%D8%B2%D8%B4%DB%8C/%D9%BE%DB%8C%D8%A7%D8%AF%D9%87-%D8%B3%D8%A7%D8%B2%DB%8C-%D8%AA%D8%A8%D9%84%DB%8C%D8%BA%D8%A7%D8%AA-%D8%AF%D8%B1-react-native-%D8%A8%D8%A7-%D8%AA%D9%BE%D8%B3%D9%84/

**Comment by kamyabsoft** [comment]
حتی اگه با --force 
هم نصب کنیم اما مترو وصل نمیشه وقتی این کتابخانه را پاک میکنم درست میشه اما وقتی نصب میشه وصل نمیشه
الان بخواییم از تپسل استفاده کنیم واقعا راهی نداره ؟

**Comment by mahdi-malv** [comment]
> با نود ۱۴ هم میتونید تستش کنید؟

این بررسی شد؟

**Comment by amirito** [comment]
> با نود ۱۴ هم میتونید تستش کنید؟

با نود ۱۶ هم حتی کار نکرد
