### ISSUE TITLE
🚀[فیچر]:  امکان انتخاب دقیق محل قرار گرفتن تبلیغ استاندارد

### ISSUE THREAD

**Issue by mdehghani65** [tapsellorg/TapsellPlusSDK-ReactNativePlugin#18]
<div dir='rtl'>

**شرح نقص یا فیچر درخواستی**  :
آیا راهی وجود دارد که محل دقیق نمایش تبلیغ استاندارد را بصورت یک container و به نسبت اجزای دیگر داخل تصویر به صورت relative تعیین کرد؟
ظاهرا در حال حاضر تبلیغ بنری استاندارد فقط در پایین ترین یا بالاترین  قسمت تصویر یا وسط آن قابل جانمایی است.

![Screenshot_2022-08-01-14-36-26](https://user-images.githubusercontent.com/28774905/182126768-99344875-7b4e-4397-a4bc-ddda55db71e2.png)

در نسخه معمولی تپسل برای ریاکت نیتیو ظاهرا یک کامپوننت بنام <BannerAd مشابه ادموب وجود داشت که ظاهرا در تپسل پلاس حذف شده
</div>

**Comment by MortezaNedaei** [comment]
سلام وقت بخیر
خیر متاسفانه در حال حاظر این امکان در تپسل پلاس وجود ندارد
