### ISSUE TITLE
در هنگام نصب sdk tapsell > Task :app:mergeDebugNativeLibs FAILEDارور  

### ISSUE THREAD

**Issue by mohammadjfadaee** [tapsellorg/TapsellPlusSDK-ReactNativePlugin#19]
<div 
![Screenshot 2022-11-09 091811](https://user-images.githubusercontent.com/95547732/200749617-4b4b0731-cdb7-4f22-b9ed-a64504879784.png)
>

> Task :app:mergeDebugNativeLibs FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings   
126 actionable tasks: 3 executed, 123 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - C:\Users\abolf\.gradle\caches\transforms-3\a8108ce710a662637a30dedebdb0a106\transformed\jetified-react-native-0.71.0-rc.0-debug\jni\arm64-v8a\libc++_shared.so
      - C:\Users\abolf\.gradle\caches\transforms-3\1a8b906c1649e97dbca55059e0091063\transformed\jetified-fbjni-0.3.0\jni\arm64-v8a\libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - C:\Users\abolf\.gradle\caches\transforms-3\a8108ce710a662637a30dedebdb0a106\transformed\jetified-react-native-0.71.0-rc.0-debug\jni\arm64-v8a\libc++_shared.so
      - C:\Users\abolf\.gradle\caches\transforms-3\1a8b906c1649e97dbca55059e0091063\transformed\jetified-fbjni-0.3.0\jni\arm64-v8a\libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s

</div>

**Comment by MortezaNedaei** [comment]
- It seems something is wrong with `jni` config in `build.gradle` file, However I'm not sure if it's related to Tapsell since it's not using `jni`
- Are you able to reproduce this problem in our sample app?
- Please check [this](https://stackoverflow.com/a/58602329/8291919) or [this link](https://stackoverflow.com/a/70893407/8291919)
