### ISSUE TITLE
ارور هنگام نصب🐛 [BUG/ERROR]

### ISSUE THREAD

**Issue by Epitomaniac** [tapsellorg/TapsellPlusSDK-ReactNativePlugin#22]
**Describe the issue**:
متاسفانه نمیتونم sdk رو نصب کنم.

**Paste the error text in your logs**:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: words@1.0.0
npm ERR! Found: react-native@0.70.5
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.70.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"0.63.4" from react-native-tapsell-plus@2.1.8-rc01
npm ERR! node_modules/react-native-tapsell-plus
npm ERR!   react-native-tapsell-plus@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**[Optionally paste the whole stacktrace for more details**:

**How to reproduce this issue:**

**App package name**: ``

**Comment by MortezaNedaei** [comment]
I believe you can fix this by `npm i --legacy-peer-deps`
However, reopen it if this won't help you

**Comment by bahmanworld** [comment]
Same
